-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myholylib` DEFAULT CHARACTER SET utf8 ;
USE `myholylib` ;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_SEDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_SEDE` (
  `ID_SEDE` INT NOT NULL,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `DIRECCION` VARCHAR(150) NOT NULL,
  `DISTRITO` VARCHAR(50) NOT NULL,
  `TELEFONO_CONTACTO` VARCHAR(15) NOT NULL,
  `CORREO_CONTACTO` VARCHAR(100) NOT NULL,
  `ACTIVA` TINYINT(0) NOT NULL,
  PRIMARY KEY (`ID_SEDE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_PERSONA` (
  `ID_PERSONA` INT NOT NULL,
  `NOMBRE_COMPLETO` VARCHAR(100) NOT NULL,
  `DIRECCION` VARCHAR(150) NOT NULL,
  `TELEFONO` VARCHAR(9) NOT NULL,
  `CORREO` VARCHAR(100) NOT NULL,
  `CONTRASENHA` VARCHAR(25) NOT NULL,
  `SEDE_IDSEDE` INT NOT NULL,
  PRIMARY KEY (`ID_PERSONA`),
  INDEX `fk_BIB_PERSONA_BIB_SEDE1_idx` (`SEDE_IDSEDE` ASC) VISIBLE,
  CONSTRAINT `fk_BIB_PERSONA_BIB_SEDE1`
    FOREIGN KEY (`SEDE_IDSEDE`)
    REFERENCES `myholylib`.`BIB_SEDE` (`ID_SEDE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_LECTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_LECTOR` (
  `ID_LECTOR` INT NOT NULL,
  `NIVEL` ENUM('A', 'B', 'C') NOT NULL COMMENT 'A:BASICO\nB:INTERMEDIO\nC:AVANZADO\n',
  `PERSONA_IDPERSONA` INT NOT NULL,
  PRIMARY KEY (`ID_LECTOR`),
  INDEX `fk_BIB_LECTOR_BIB_PERSONA_idx` (`PERSONA_IDPERSONA` ASC) VISIBLE,
  CONSTRAINT `fk_BIB_LECTOR_BIB_PERSONA`
    FOREIGN KEY (`PERSONA_IDPERSONA`)
    REFERENCES `myholylib`.`BIB_PERSONA` (`ID_PERSONA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_BIBLIOTECARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_BIBLIOTECARIO` (
  `ID_BIBLIOTECARIO` INT NOT NULL,
  `TURNO` ENUM('Manhana', 'Tarde', 'Noche') NULL,
  `FECHA_CONTRATO_INI` DATE NULL,
  `FECHA_CONTRATO_FIN` DATE NULL,
  `VIGENTE` TINYINT(0) NULL,
  `PERSONA_IDPERSONA` INT NOT NULL,
  PRIMARY KEY (`ID_BIBLIOTECARIO`),
  INDEX `fk_BIB_BIBLIOTECARIO_BIB_PERSONA1_idx` (`PERSONA_IDPERSONA` ASC) VISIBLE,
  CONSTRAINT `fk_BIB_BIBLIOTECARIO_BIB_PERSONA1`
    FOREIGN KEY (`PERSONA_IDPERSONA`)
    REFERENCES `myholylib`.`BIB_PERSONA` (`ID_PERSONA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_PRESTAMO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_PRESTAMO` (
  `ID_PRESTAMO` INT NOT NULL,
  `FECHA_SOLICITUD` DATE NULL,
  `FECHA_PRESTAMO` DATE NOT NULL,
  `FECHA_DEVOLUCION` DATE NOT NULL,
  `LECTOR_IDLECTOR` INT NOT NULL,
  PRIMARY KEY (`ID_PRESTAMO`),
  INDEX `fk_BIB_PRESTAMO_BIB_LECTOR1_idx` (`LECTOR_IDLECTOR` ASC) VISIBLE,
  CONSTRAINT `fk_BIB_PRESTAMO_BIB_LECTOR1`
    FOREIGN KEY (`LECTOR_IDLECTOR`)
    REFERENCES `myholylib`.`BIB_LECTOR` (`ID_LECTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_REPORTE_SEDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_REPORTE_SEDE` (
  `ANHIO` INT NOT NULL,
  `MES` INT NOT NULL,
  `PRESTAMO_IDPRESTAMO` INT NOT NULL,
  `LECTOR_ID_LECTOR` INT NOT NULL,
  `SEDE_IDSEDE` INT NOT NULL,
  PRIMARY KEY (`ANHIO`, `MES`, `PRESTAMO_IDPRESTAMO`, `LECTOR_ID_LECTOR`, `SEDE_IDSEDE`),
  INDEX `fk_BIB_REPORTE_SEDE_BIB_SEDE1_idx` (`SEDE_IDSEDE` ASC) VISIBLE,
  INDEX `fk_BIB_REPORTE_SEDE_BIB_PRESTAMO_idx` (`PRESTAMO_IDPRESTAMO` ASC) VISIBLE,
  INDEX `fk_BIB_REPORTE_SEDE_BIB_LECTOR_idx` (`LECTOR_ID_LECTOR` ASC) VISIBLE,
  CONSTRAINT `fk_BIB_REPORTE_SEDE_BIB_SEDE1`
    FOREIGN KEY (`SEDE_IDSEDE`)
    REFERENCES `myholylib`.`BIB_SEDE` (`ID_SEDE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BIB_REPORTE_SEDE_BIB_PRESTAMO`
    FOREIGN KEY (`PRESTAMO_IDPRESTAMO`)
    REFERENCES `myholylib`.`BIB_PRESTAMO` (`ID_PRESTAMO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BIB_REPORTE_SEDE_BIB_LECTOR`
    FOREIGN KEY (`LECTOR_ID_LECTOR`)
    REFERENCES `myholylib`.`BIB_LECTOR` (`ID_LECTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_REPORTE_GENERAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_REPORTE_GENERAL` (
  `ANHIO` INT NOT NULL,
  `MES` INT NOT NULL,
  `PRESTAMO_IDPRESTAMO` INT NOT NULL,
  `LECTOR_IDLECTOR` INT NOT NULL,
  PRIMARY KEY (`ANHIO`, `LECTOR_IDLECTOR`, `PRESTAMO_IDPRESTAMO`, `MES`),
  INDEX `fk_BIB_REPORTE_GENERAL_BIB_PRESTAMO_idx` (`PRESTAMO_IDPRESTAMO` ASC) VISIBLE,
  INDEX `fk_BIB_REPORTE_GENERAL_BIB_LECTOR_idx` (`LECTOR_IDLECTOR` ASC) VISIBLE,
  CONSTRAINT `fk_BIB_REPORTE_GENERAL_BIB_PRESTAMO`
    FOREIGN KEY (`PRESTAMO_IDPRESTAMO`)
    REFERENCES `myholylib`.`BIB_PRESTAMO` (`ID_PRESTAMO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BIB_REPORTE_GENERAL_BIB_LECTOR`
    FOREIGN KEY (`LECTOR_IDLECTOR`)
    REFERENCES `myholylib`.`BIB_LECTOR` (`ID_LECTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_EDITORIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_EDITORIAL` (
  `ID_EDITORIAL` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `SITIOWEB` VARCHAR(100) NULL,
  `PAIS` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_EDITORIAL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_MATERIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_MATERIAL` (
  `ID_MATERIAL` INT NOT NULL,
  `TITULO` VARCHAR(100) NULL,
  `EDICION` VARCHAR(45) NULL,
  `NIVEL` ENUM('A', 'B', 'C') NULL COMMENT 'A:BASICO\nB:INTERMEDIO\nC:AVANZADO',
  `ANHIO_PUBLICACION` INT NULL,
  `EDITORIAL_IDEDITORIAL` INT NOT NULL,
  PRIMARY KEY (`ID_MATERIAL`),
  INDEX `fk_BIB_MATERIAL_MAT_EDITORIAL1_idx` (`EDITORIAL_IDEDITORIAL` ASC) VISIBLE,
  CONSTRAINT `fk_BIB_MATERIAL_MAT_EDITORIAL1`
    FOREIGN KEY (`EDITORIAL_IDEDITORIAL`)
    REFERENCES `myholylib`.`BIB_EDITORIAL` (`ID_EDITORIAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_EJEMPLAR_DIGITAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_EJEMPLAR_DIGITAL` (
  `ID_EJEMPLAR_DIG` INT NOT NULL,
  `FORMATO` ENUM('A', 'B', 'C', 'D') NULL COMMENT 'A:MP3\nB:PDF\nC:CBR\nD:PPT',
  `MATERIAL_IDMATERIAL` INT NOT NULL,
  PRIMARY KEY (`ID_EJEMPLAR_DIG`),
  INDEX `fk_MAT_EJEMPLAR_DIGITAL_BIB_MATERIAL1_idx` (`MATERIAL_IDMATERIAL` ASC) VISIBLE,
  CONSTRAINT `fk_MAT_EJEMPLAR_DIGITAL_BIB_MATERIAL1`
    FOREIGN KEY (`MATERIAL_IDMATERIAL`)
    REFERENCES `myholylib`.`BIB_MATERIAL` (`ID_MATERIAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_TEMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_TEMA` (
  `ID_TEMA` INT NOT NULL,
  `DESCRIPCION` VARCHAR(100) NOT NULL,
  `CATEGORIA` ENUM('A', 'B') NOT NULL COMMENT 'A:GENERO\nB:EDAD',
  PRIMARY KEY (`ID_TEMA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_EJEMPLAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_EJEMPLAR` (
  `ID_EJEMPLAR` INT NOT NULL,
  `FECHA_ADQUISICION` DATE NOT NULL,
  `DISPONIBLE` TINYINT(0) NOT NULL,
  `UBICACION` VARCHAR(70) NOT NULL,
  `SEDE_IDSEDE` INT NOT NULL,
  `MATERIAL_IDMATERIAL` INT NOT NULL,
  PRIMARY KEY (`ID_EJEMPLAR`),
  INDEX `fk_MAT_EJEMPLAR_BIB_SEDE1_idx` (`SEDE_IDSEDE` ASC) VISIBLE,
  INDEX `fk_MAT_EJEMPLAR_BIB_MATERIAL1_idx` (`MATERIAL_IDMATERIAL` ASC) VISIBLE,
  CONSTRAINT `fk_MAT_EJEMPLAR_BIB_SEDE1`
    FOREIGN KEY (`SEDE_IDSEDE`)
    REFERENCES `myholylib`.`BIB_SEDE` (`ID_SEDE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MAT_EJEMPLAR_BIB_MATERIAL1`
    FOREIGN KEY (`MATERIAL_IDMATERIAL`)
    REFERENCES `myholylib`.`BIB_MATERIAL` (`ID_MATERIAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_SANCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_SANCION` (
  `ID_SANCION` INT NOT NULL,
  `TIPO` ENUM('Danho') NOT NULL,
  `FECHA` DATE NOT NULL,
  `MONTO` DOUBLE NULL,
  `DURACION` DATE NOT NULL,
  `DESCRIPCION` VARCHAR(150) NULL,
  `BIB_SANCIONcol` VARCHAR(45) NOT NULL,
  `PRESTAMO_IDPRESTAMO` INT NOT NULL,
  PRIMARY KEY (`ID_SANCION`),
  INDEX `fk_BIB_SANCION_BIB_PRESTAMO1_idx` (`PRESTAMO_IDPRESTAMO` ASC) VISIBLE,
  CONSTRAINT `fk_BIB_SANCION_BIB_PRESTAMO1`
    FOREIGN KEY (`PRESTAMO_IDPRESTAMO`)
    REFERENCES `myholylib`.`BIB_PRESTAMO` (`ID_PRESTAMO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_AUTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_AUTOR` (
  `ID_AUTOR` INT NOT NULL,
  `NOMBRE_COMPLETO` VARCHAR(150) NOT NULL,
  `NACIONALIDAD` VARCHAR(50) NOT NULL,
  `ACTIVO` TINYINT(0) NOT NULL,
  `CANTIDAD_OBRAS` INT NULL,
  PRIMARY KEY (`ID_AUTOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_PRESTAMO_EJEMPLAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_PRESTAMO_EJEMPLAR` (
  `PRESTAMO_IDPRESTAMO` INT NOT NULL,
  `EJEMPLAR_IDEJEMPLAR` INT NOT NULL,
  `ESTADO` ENUM('A', 'B', 'C', 'D') NOT NULL COMMENT 'A:SOLICITADO\nB:PRESTADO\nC:DEVUELTO\nD:ATRASADO',
  `FECHA_REAL_DEVOLUCION` DATE NOT NULL,
  PRIMARY KEY (`PRESTAMO_IDPRESTAMO`, `EJEMPLAR_IDEJEMPLAR`),
  INDEX `fk_BIB_PRESTAMO_has_MAT_EJEMPLAR_MAT_EJEMPLAR1_idx` (`EJEMPLAR_IDEJEMPLAR` ASC) VISIBLE,
  INDEX `fk_BIB_PRESTAMO_has_MAT_EJEMPLAR_BIB_PRESTAMO1_idx` (`PRESTAMO_IDPRESTAMO` ASC) VISIBLE,
  CONSTRAINT `fk_BIB_PRESTAMO_has_MAT_EJEMPLAR_BIB_PRESTAMO1`
    FOREIGN KEY (`PRESTAMO_IDPRESTAMO`)
    REFERENCES `myholylib`.`BIB_PRESTAMO` (`ID_PRESTAMO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BIB_PRESTAMO_has_MAT_EJEMPLAR_MAT_EJEMPLAR1`
    FOREIGN KEY (`EJEMPLAR_IDEJEMPLAR`)
    REFERENCES `myholylib`.`BIB_EJEMPLAR` (`ID_EJEMPLAR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_MATERIAL_TEMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_MATERIAL_TEMA` (
  `MATERIAL_IDMATERIAL` INT NOT NULL,
  `TEMA_IDTEMA` INT NOT NULL,
  PRIMARY KEY (`MATERIAL_IDMATERIAL`, `TEMA_IDTEMA`),
  INDEX `fk_BIB_MATERIAL_has_MAT_TEMA_MAT_TEMA1_idx` (`TEMA_IDTEMA` ASC) VISIBLE,
  INDEX `fk_BIB_MATERIAL_has_MAT_TEMA_BIB_MATERIAL1_idx` (`MATERIAL_IDMATERIAL` ASC) VISIBLE,
  CONSTRAINT `fk_BIB_MATERIAL_has_MAT_TEMA_BIB_MATERIAL1`
    FOREIGN KEY (`MATERIAL_IDMATERIAL`)
    REFERENCES `myholylib`.`BIB_MATERIAL` (`ID_MATERIAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BIB_MATERIAL_has_MAT_TEMA_MAT_TEMA1`
    FOREIGN KEY (`TEMA_IDTEMA`)
    REFERENCES `myholylib`.`BIB_TEMA` (`ID_TEMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myholylib`.`BIB_MATERIAL_AUTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myholylib`.`BIB_MATERIAL_AUTOR` (
  `MATERIAL_IDMATERIAL` INT NOT NULL,
  `AUTOR_IDAUTOR` INT NOT NULL,
  PRIMARY KEY (`MATERIAL_IDMATERIAL`, `AUTOR_IDAUTOR`),
  INDEX `fk_BIB_MATERIAL_has_BIB_AUTOR_BIB_AUTOR1_idx` (`AUTOR_IDAUTOR` ASC) VISIBLE,
  INDEX `fk_BIB_MATERIAL_has_BIB_AUTOR_BIB_MATERIAL1_idx` (`MATERIAL_IDMATERIAL` ASC) VISIBLE,
  CONSTRAINT `fk_BIB_MATERIAL_has_BIB_AUTOR_BIB_MATERIAL1`
    FOREIGN KEY (`MATERIAL_IDMATERIAL`)
    REFERENCES `myholylib`.`BIB_MATERIAL` (`ID_MATERIAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BIB_MATERIAL_has_BIB_AUTOR_BIB_AUTOR1`
    FOREIGN KEY (`AUTOR_IDAUTOR`)
    REFERENCES `myholylib`.`BIB_AUTOR` (`ID_AUTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;